### ISSUE TITLE
Consumer not consuming

### ISSUE THREAD

**Issue by stepanov1975** [eikek/docspell#1244]
I am running dockspell in docker using docker-compose
Consumer configured as below
I have collective "home" (i am logging in as "home/alex")
If I put file in ./consume_docs (mapped to /opt/docs) directory the log says:
```
Got: /opt/docs/0000067.pdf
Cmd: Watch: Error finding collective: The collective could not be deduced for /opt/docs/0000067.pdf. Make sure there is a subdirectory with the name of the collective below /opt/docs
Watching directory (Recursive): /opt/docs
```

If I create a directory home inside ./consume_docs and put the file in this directory I am getting:

```
Got: /opt/docs/home
Cmd: Watch: Error finding collective: The collective could not be deduced for /opt/docs/home. Make sure there is a subdirectory with the name of the collective below /opt/docs
Watching directory (Recursive): /opt/docs
```

Configuration:
```
consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:..."
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - ./consume_docs:/opt/docs
    depends_on:
      - restserver

```
