### ISSUE TITLE
Mutiple joex containers hava same app-id  in 'job' table 'worker' column.

### ISSUE THREAD

**Issue by ohagene** [eikek/docspell#1551]
Hi, I started mutiple joex containers to increase processing speed. I have changed the app-id in docker-compose file, and the the joex startup log showed that the app-id had been changed, but 'job' table's 'worker' column are all 'joex1', and web-ui processing queue logs are also all 'joex1'.  What was wrong?
docker-compose file :
```yml
  joex1:
    image: docspell/joex:latest 
    container_name: docspell-joex1
    restart: unless-stopped
    environment:
      - DOCSPELL_JOEX_APP__ID=joex1
      - DOCSPELL_JOEX_SCHEDULER_POOL__SIZE=2
      - DOCSPELL_JOEX_BASE__URL=http://docspell-joex1:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      -  ...

  joex2:
    image: docspell/joex:latest 
    container_name: docspell-joex2
    restart: unless-stopped
    environment:
      - DOCSPELL_JOEX_APP__ID=joex2
      - DOCSPELL_JOEX_SCHEDULER_POOL__SIZE=2
      - DOCSPELL_JOEX_BASE__URL=http://docspell-joex2:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      -  ...

  joex3:
    image: docspell/joex:latest 
    container_name: docspell-joex3
    restart: unless-stopped
    environment:
      - DOCSPELL_JOEX_APP__ID=joex3
      - DOCSPELL_JOEX_SCHEDULER_POOL__SIZE=2
      - DOCSPELL_JOEX_BASE__URL=http://docspell-joex3:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      -  ...
```
joex6 start up logs:
```
docspell-joex6  | Starting unoconv listener
docspell-joex6  | May 16, 2022 10:35:14 AM org.jline.utils.Log logr
docspell-joex6  | WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
docspell-joex6  | 2022.05.16 10:35:14:563 io-compute-29 INFO docspell.config.ConfigFactory.default:44
docspell-joex6  |     Using config from environment variables!
docspell-joex6  | 2022.05.16 10:35:15:0000 [io-comp...] [INFO ] docspell.joex.Main.run:37 -
docspell-joex6  | ***>  ______                          _ _
docspell-joex6  | ***>  |  _  \                        | | |
docspell-joex6  | ***>  | | | |___   ___ ___ _ __   ___| | |
docspell-joex6  | ***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
docspell-joex6  | ***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
docspell-joex6  | ***>  |___/ \___/ \___|___/ .__/ \___|_|_|
docspell-joex6  | ***>                      | |
docspell-joex6  | ***>                      |_| v0.34.0 (#c6da3eb0)
docspell-joex6  | ***>  << JOEX >>
docspell-joex6  | ***>  Id:       joex6
docspell-joex6  | ***>  Base-Url: http://docspell-joex6:7878
docspell-joex6  | ***>  Database: jdbc:postgresql://xxxx:5432/docspell
docspell-joex6  | ***>  Fts:      PostgreSQL(default)
docspell-joex6  | ***>  Config:
docspell-joex6  | ***>  FileRepo: DefaultDatabase(true)
```
