### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by typkrft** [eikek/docspell#1717]
On a fresh docker setup of Docspell. I am able to get to the login screen, however if it reload it sometimes I get a 403 Forbidden and sometimes the login shows up. I am never able to login though. It does work reliably at my local ip and port. For my reverse I'm using traefik and authelia. I am not using OIDC. This config works work 88 other other containers and I have deployed Docspell successfully in the past. 

```LOGS
2022.08.25 08:24:38:0019 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 403 Forbidden
2022.08.25 08:24:38:0006 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v1/sec/usertask/periodicquery
2022.08.25 08:24:38:0007 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 403 Forbidden
2022.08.25 08:24:38:0008 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v1/sec/addon/archive
2022.08.25 08:24:38:0009 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 403 Forbidden
2022.08.25 08:24:38:0004 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v1/sec/folder?q=&sort=name
2022.08.25 08:24:38:0005 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 403 Forbidden
2022.08.25 08:24:38:0020 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v1/sec/notification/hook
2022.08.25 08:24:38:0021 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 403 Forbidden
2022.08.25 08:24:38:0010 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v1/sec/user/otp/state
2022.08.25 08:24:38:0011 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 403 Forbidden
2022.08.25 08:24:38:0006 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 GET /api/v1/sec/user
2022.08.25 08:24:38:0007 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 403 Forbidden
```

Relevant Traefik Configs
middlewares.yml
```YAML
http:
  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.domain.com"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"

   default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true

    auth-chain:               
      chain:                     
        middlewares:             
        - authelia
        - default-headers
```

services.yml
```YAML
http:
  routers:
    docspell:
      entryPoints:
        - "websecure"
      rule: "Host(`docspell.domain.com`)"
      middlewares:
        - auth-chain
      tls: {}
      service: docspell

  services:
    docspell:
      loadBalancer:
        servers:
          - url: "http://10.10.10.4:7015"
        passHostHeader: true
```

Authelia Config
```YAML
access_control:
  default_policy: deny
  rules:
    - domain: docspell.domain.com
      policy: one_factor
```
Docker Compose
docspell.yml
```YAML
services:
  docspell:
    image: docspell/restserver:latest
    container_name: docspell
    restart: unless-stopped
    ports:
      - "7015:7880"
    environment:
      TZ: US/Eastern
      DOCSPELL_SERVER_INTERNAL__URL: http://docspell:7880
      DOCSPELL_SERVER_BASE__URL: https://docspell.domain.com
      DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET: passphrase
      DOCSPELL_SERVER_AUTH_SERVER__SECRET: passphrase
      DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD: passphrase
      DOCSPELL_SERVER_BACKEND_JDBC_URL: jdbc:postgresql://docspell-db:5432/docspell_db
      DOCSPELL_SERVER_BACKEND_JDBC_USER: docspell_admin
      DOCSPELL_SERVER_BIND_ADDRESS: 0.0.0.0
      DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED: "true"
      DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL: http://docspell-solr:8983/solr/docspell
      DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED: "true"
      DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED: "true"
      DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE: passphrase
    depends_on:
      - docspell-solr

  docspell-db:
    image: postgres:14.2
    container_name: docspell-db
    restart: unless-stopped
    volumes:
      - /docker_storage/docspell/db:/var/lib/postgresql/data/
      - /docker_storage/docspell/backups:/backups
    environment:
      POSTGRES_USER: docspell_admin
      POSTGRES_PASSWORD: passphrase
      POSTGRES_DB: docspell_db
    ports: 
      - 7016:5432
    labels:
      db_backup: "true"
      db_type: psql
      db_user: docspell_admin
      db_pass: passphrase
      db_name: docspell_db

  docspell-joex:
    image: docspell/joex:latest
    container_name: docspell-joex
    command:
      - -J-Xmx3G
      - -J-XX:+UseG1GC
    restart: unless-stopped
    environment:
      TZ: US/Eastern
      DOCSPELL_JOEX_BASE__URL: http://docspell-joex:7878
      DOCSPELL_JOEX_BIND_ADDRESS: 0.0.0.0
      DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED: "true"
      DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL: http://docspell-solr:8983/solr/docspell
      DOCSPELL_JOEX_JDBC_PASSWORD: passphrase
      DOCSPELL_JOEX_JDBC_URL: jdbc:postgresql://docspell-db:5432/docspell_db
      DOCSPELL_JOEX_JDBC_USER: docspell_admin
    ports:
      - "7017:7878"
    depends_on:
      - docspell-solr

  docspell-consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    user: "1000:1000"
    command:
      - dsc
      - "-d"
      - "http://docspell:7880"
      - "upload"
      - "--poll"
      -  "60"
      - "--traverse"
      # - "--delete"
      - "-i"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:passphrase"
      - "/opt/docs"
    restart: unless-stopped
    #    volumes:
    #      - na:/opt/docs/na
    depends_on:
      - docspell

  docspell-solr:
    user: "1000:1000"
    image: solr:8
    container_name: docspell-solr
    restart: unless-stopped
    volumes:
      - /docker_storage/docspell/solr:/var/solr
    command:
      - solr-precreate
      - docspell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s
```
