### ISSUE TITLE
Mobile View not working anymore

### ISSUE THREAD

**Issue by Madnex** [eikek/docspell#1720]
Hi! I have a weird problem with my iPhone. I am sure it was working fine until recently. Now the content will just not show up anymore. See the attached gif. I tried reloading the page, restarting the docspell server (docker), using a different browser on my phone (Firefox, Safari) but it just won't show up... Even after waiting several minutes.

On my computer it works fine though.

Any ideas what's going wrong here?

![ios](https://user-images.githubusercontent.com/14137610/187279210-4757d6b1-db05-4421-a94c-e459a2303f78.gif)

**Comment by eikek** [comment]
Oh no, I have no idea what's wrong! It works on my Android phone - tried with a few browsers. I don't have an iphone to test with :/. Could there be some browser addon or anything like this? To me it looks like an js problem.

**Comment by Madnex** [comment]
I tried resetting Safari data. It worked in that way, that I could login again and see some documents. However, that lasted only a few clicks.. Then it's the same situation again :/ 

I tried with and without content blockers, with "Request Desktop Website" and "Request Mobile Website". No extensions are enabled. 

After some investigation I believe it is affecting Safari in general. The exact same issue occurred on my iPad and Mac. Firefox and Chrome are working fine with docspell on my Mac though. I checked the web console and besides from a few errors about not finding some resources in all three browsers (Chrome, Firefox, Safari) there is one error **only appearing in Safari**:

```
Failed to load resource: the server responded with a status of 404 ()
https://docspell.address/app/assets/docspell-webapp/0.38.0/docspell-query-opt.js.map
```
 
Do you think this could be the reason?
It looks to me that something is going wrong with the login. After entering the credentials there is no redirection, it only says "Login successful". Then after reloading the page I have the issue that is shown.

**Comment by eikek** [comment]
> Do you think this could be the reason?

I doubt it, tbh. The `.map` file is to my knowledge sometimes provided for debugging purposes. It contains infos that have been stripped from the downsized-scrambled js package. But docspell doesn't provide it :) - so the 404 is ok to me.

The webapp is essentially one js file. If the login is not working correctly, I think this is just a symptom for not working in general. When you reload the page after loggin in, do you see some 403 (Forbidden) responses in the developter-tools maybe? It sounds to me as if the elm runtime breaks on something - are there any JS errors in the console?

**Comment by Madnex** [comment]
Here is what I get in the console right after I click login and the message "Login successful" appears:

<img width="1769" alt="grafik" src="https://user-images.githubusercontent.com/14137610/187598277-1726d3c7-5146-40fa-87c0-66a34b69ecd6.png">

The first two lines are from loading the page (before login step), hence the first two 403 are expected I believe.
Does this help you?

**Comment by eikek** [comment]
I believe the "security error" is the problem. It also refuses to create the websocket connection. Can it be that your domain is no the same as "base-url" in the config? Or that you are using https and http at the same time?

**Comment by Madnex** [comment]
I did not change the "base-url" so far. Now I tried changing it (I'm using docker-compose, and nginx as reverse proxy) by adding an environment variable in the docker-compose.yml:

```
restserver:
    image: docspell/restserver:latest
    container_name: docspell-restserver
    restart: unless-stopped
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_SERVER_BASE__URL=https://my.domain.com
      - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=mysecret
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=myothersecret
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=mypass
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:postgresql://db:5432/dbname
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=myuser
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=myheadervalue

...
```
This did not change anything though. It is working as expected in Firefox and Chrome but won't work in Safari. 
Everything requested from outside is redirected to https.

Does this help?
