### ISSUE TITLE
Newbie question: change storage to file-system

### ISSUE THREAD

**Issue by grkngls** [eikek/docspell#1757]
Hi

I'm having running docspell in docker (portainer) on my Synology. Everything works as I want.

Only I want my PDFs stored on a filesystem (on my synology) not in a database (to have access with other apps).

So I added following ENV-Variables to the containers:

docspell-joex:

- DOCSPELL_JOEX_FILES_DEFAULT__STORE="filesystem"
- DOCSPELL_JOEX_FILES_STORES_DATABASE_ENABLED=false
- DOCSPELL_JOEX_FILES_STORES_FILESYSTEM_ENABLED=true
- DOCSPELL_JOEX_FILES_STORES_FILESYSTEM_TYPE="file-system"
- DOCSPELL_JOEX_FILES_STORES_FILESYSTEM_DIRECTORY=/volume1/docker/docspell 

docspell-restserver:

- DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE="filesystem"
- DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_ENABLED=true
- DOCSPELL_SERVER_BACKEND_FILES_STORES_DATABASE_ENABLED=false
- DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_TYPE="file-system"
- DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_DIRECTORY=/volume1/docker/docspell  

I read this here: https://docspell.org/docs/configure/defaults/#default-configuration

But after that changes docspell won't start. Where did I make a mistake?

best regards
grkngls

**Comment by eikek** [comment]
Hey @grkngls - what errors are shown to you on startup? This guide might also be helpful in case you didn't find it yet: https://docspell.org/docs/configure/file-backends/

**Comment by eikek** [comment]
Are there any error messages - or are the files still stored in the database? On startup a banner is shown with important configuration - can you look what it says regarding to the file store?

**Comment by grkngls** [comment]
No error. They are still stored in the database. So I think. How can I prove where the files are stored?
I can't see a banner on startup

**Comment by eikek** [comment]
The banner I mean looks like this:
```
restserver ***>  ______                          _ _
restserver ***>  |  _  \                        | | |
restserver ***>  | | | |___   ___ ___ _ __   ___| | |
restserver ***>  | | | / _ \ / __/ __| '_ \ / _ \ | |
restserver ***>  | |/ / (_) | (__\__ \ |_) |  __/ | |
restserver ***>  |___/ \___/ \___|___/ .__/ \___|_|_|
restserver ***>                      | |
restserver ***>                      |_| v0.39.0-SNAPSHOT (#ad7bea35)
restserver ***>  << REST Server >>
restserver ***>  Id:       test1
restserver ***>  Base-Url: http://localhost:7880
restserver ***>  Database: jdbc:h2:///home/workspace/projects/docspell/local/docspell-new.db;MODE=Post
greSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE
restserver ***>  Fts:      Solr(http://localhost:8983/solr/docspell_dev_h2)
restserver ***>  Config:   /home/workspace/projects/docspell/local/dev.conf
restserver ***>  FileRepo: DefaultDatabase(true)
```
This is logged on startup - the last line indicates the configured file store. Maybe the config was not picked up, then it would show `DefaultDatabase(true)` as above.

**Comment by grkngls** [comment]
Oh. Sorry, for misunderstanding.

`***>  FileRepo: FileSystem(true,/volume1/docker/docspell)`

But the volume /volume1/docker/docspell look like this:
![CleanShot 2022-09-26 at 18 16 55](https://user-images.githubusercontent.com/11460671/192328352-f1aeafbc-121c-42c4-8f6a-736c0218738b.png)

No PDF in it.

And now docspell didn't show my the preview anymore :/

![CleanShot 2022-09-26 at 18 18 51](https://user-images.githubusercontent.com/11460671/192328744-07cd2cc0-a445-4d48-bdfd-fc0605519cbb.png)

**Comment by eikek** [comment]
The screenshot could be fine, is your collective named "docs"? Is the "docs" folder empty?

Regarding the preview: is this a document you uploaded with filestorage=filesystem active? Or was it uploaded before (when filestorage=database was in use)?

**Comment by grkngls** [comment]
... oh. So many other things didn't work:
- I can't see the extracted Meta Data.
- No preview Thumbnail
- only one corresponding per item
- file-storeage seams not working

But I think these are al problems in my (docker) installation

**Comment by grkngls** [comment]
`The screenshot could be fine, is your collective named "docs"? Is the "docs" folder empty?`
Yes. the folder 'docs' is empty

'Regarding the preview: is this a document you uploaded with filestorage=filesystem active?'
Yes. The PDF is uploaded during filestorage=filesystem

**Comment by eikek** [comment]
Do you see any errors in the log? It could be a permission problem. Can the user running docspell (joex and restserver) read and write to that directory? The extracted metadata is not very likely to be related to the file storage, though.

**Comment by grkngls** [comment]
Using Portainer I can look execute the console on the restserver. Login as "root"

There I can see my /volume1/docker/docspell. But there I see my username from my Synology als folder. There is another folder named 'attachmentsource'

These folder I can't see on my Synology.

Trying to login the console with my username don't work.  I think you're right: it seems to be an permission problem.

This is my compose file:
```
version: '3.8'
services:

  # The restserver and joex containers defined here are configured
  # using env variables. Both must connect to the same database and
  # solr instance. More information on configuring can be found here:
  # https://docspell.org/docs/configure
  #
  # Please replace the values of the following with a custom secret
  # string:
  #
  # - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET
  # - DOCSPELL_SERVER_AUTH_SERVER__SECRET
  # - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE
  #   (use the same value at the consumedir container!)
  #
  # After creating an account, you may want to set signup mode to
  # "closed" or to "invite". When using invite, you must also set
  # DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD to some
  # secret.
  restserver:
    image: docspell/restserver:latest
    container_name: docspell-restserver
    restart: unless-stopped
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=admin123
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=dbpass
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:postgresql://db:5432/dbname
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=dbuser
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=integration-password123
      - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
      - DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD=     
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
      - DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE=filesystem
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_ENABLED=true
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_DATABASE_ENABLED=true
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_TYPE=file-system
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_DIRECTORY=/volume1/docker/docspell
    depends_on:
      - solr
      - db

  joex:
    image: docspell/joex:latest
    container_name: docspell-joex
    ## For more memory add corresponding arguments, like below. Also see
    ## https://docspell.org/docs/configure/#jvm-options
    # command:
    #   - -J-Xmx3G
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_JOEX_APP__ID=joex1
      - DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_BASE__URL=http://docspell-joex:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_JOEX_JDBC_PASSWORD=dbpass
      - DOCSPELL_JOEX_JDBC_URL=jdbc:postgresql://db:5432/dbname
      - DOCSPELL_JOEX_JDBC_USER=dbuser
      - DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER=docker,trivial
      - DOCSPELL_JOEX_FILES_DEFAULT__STORE=filesystem
      - DOCSPELL_JOEX_FILES_STORES_DATABASE_ENABLED=true
      - DOCSPELL_JOEX_FILES_STORES_FILESYSTEM_ENABLED=true
      - DOCSPELL_JOEX_FILES_STORES_FILESYSTEM_TYPE=file-system
      - DOCSPELL_JOEX_FILES_STORES_FILESYSTEM_DIRECTORY=/volume1/docker/docspell
    ports:
      - "7878:7878"
    depends_on:
      - solr
      - db
    ## Uncomment when using the "docker" runner with addons
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    #   - /tmp:/tmp

  # The consumedir container watches a directory for files to upload
  # to docspell restserver. This uses the `dsc` tool. For information
  # on the available options, see `dsc --help`.
  # https://github.com/docspell/dsc
  #
  # The value after `Docspell-Integration` must match the secret
  # specified at the restserver via
  # DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE.
  #
  # The --not-matches "**/.*" option is to exclude hidden files.
  consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:integration-password123"
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - /volume1/docker/docspell/docs:/opt/docs
    depends_on:
      - restserver

  db:
    image: postgres:14.5
    container_name: postgres_db_docspell
    restart: unless-stopped
    volumes:
      - /volume1/docker/docspell/postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname

  solr:
    image: solr:9
    container_name: docspell-solr
    restart: unless-stopped
    volumes:
      - docspell-solr_data:/var/solr
    command:
      - solr-precreate
      - docspell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s

volumes:
  docspell-postgres_data:
  docspell-solr_data:
```
There I miss PUID=1026 (that's my ID from my user)
