### ISSUE TITLE
Replace unoconv with unoserv

### ISSUE THREAD

**Issue by eikek** [eikek/docspell#1888]
Unoconv has been rewritten and is now named [unoserver](https://github.com/unoconv/unoserver/). The docker images and default configuration should be changed accordingly.

**Comment by PaulMcF1987** [comment]
I am having difficulty converting .docx to .pdf
I have played around with the YAML etc to try and fix

Either
The file gets stuck in processing
or
The file stays waiting and doesnt move to processing
or
The file goes into processing for 1s, and the file is added to the list but there is no PDF preview

My YAML
```yaml
name: docspell

services:
  restserver:
    image: ghcr.io/docspell/restserver:latest
    container_name: docspell-restserver
    restart: unless-stopped
    ports:
      - "7880:7880"

    environment:
      TZ: Europe/London

      DOCSPELL_SERVER_INTERNAL__URL: http://docspell-restserver:7880

      DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET: ${ENDPOINT_SECRET}
      DOCSPELL_SERVER_AUTH_SERVER__SECRET: ${SERVER_SECRET}
      DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE: ${INTEGRATION_SECRET}

      DOCSPELL_SERVER_BACKEND_JDBC_URL: jdbc:postgresql://1Panel_Postgres:5432/${DBNAME}
      DOCSPELL_SERVER_BACKEND_JDBC_USER: ${DBUSER}
      DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD: ${DBPASS}

      DOCSPELL_SERVER_BACKEND_SIGNUP_MODE: open

      DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED: "true"
      DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL: http://solr:8983/solr/docspell

      DOCSPELL_SERVER_BIND_ADDRESS: 0.0.0.0

    depends_on:
      - solr

    networks:
      - 1panel-network


  joex:
    image: ghcr.io/docspell/joex:latest
    container_name: docspell-joex
    restart: unless-stopped

    environment:
      TZ: Europe/London

      DOCSPELL_JOEX_APP__ID: joex1
      DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME: joex1
      DOCSPELL_JOEX_SCHEDULER_NAME: joex1

      DOCSPELL_JOEX_BASE__URL: http://docspell-joex:7878
      DOCSPELL_JOEX_BIND_ADDRESS: 0.0.0.0

      DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED: "true"
      DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL: http://solr:8983/solr/docspell

      DOCSPELL_JOEX_JDBC_URL: jdbc:postgresql://1Panel_Postgres:5432/${DBNAME}
      DOCSPELL_JOEX_JDBC_USER: ${DBUSER}
      DOCSPELL_JOEX_JDBC_PASSWORD: ${DBPASS}

      # ✅ FIX: valid executor runners only
      DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER: "docker,trivial"

      # (optional but commonly used in official configs)
      DOCSPELL_JOEX_CONVERT_HTML__CONVERTER: "weasyprint"

    ports:
      - "7878:7878"

    depends_on:
      - solr
      - restserver

    networks:
      - 1panel-network


  solr:
    image: solr:10
    container_name: docspell-solr
    restart: unless-stopped

    command:
      - bash
      - -c
      - "precreate-core docspell; exec solr start -f --user-managed"

    environment:
      SOLR_OPTS: "-Dsolr.modules=analysis-extras"

    volumes:
      - ./data/solr_data:/var/solr

    networks:
      1panel-network:
        aliases:
          - solr
          - docspell-solr


  consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    restart: unless-stopped

    command:
      - dsc
      - -d
      - http://docspell-restserver:7880
      - watch
      - --delete
      - -ir
      - --not-matches
      - "**/.*"
      - --header
      - Docspell-Integration:integration-secret
      - /opt/docs

    volumes:
      - ./data/docs:/opt/docs

    depends_on:
      - restserver

    networks:
      - 1panel-network


networks:
  1panel-network:
    external: true
```

Is there anything I should change?
