### ISSUE TITLE
[DOCUMENTATION] OIDC / OpenID Connect with Authelia

### ISSUE THREAD

**Issue by Enjoyed** [eikek/docspell#1897]
Hello! This is merely informative as i had way too much trouble and couldn't find much information about the issues. Now that i got it working (finally!), i'm sharing my end result for anyone with the same issue!
In my setup, im using Authelia for authorization, and traefik as a proxy. Also using MYSQL instead of postgresql.

!!! You CAN'T MIX environment variables and configuration file! And when using config file... well lots of stuff to set.

So, the "end" configuration would be:
For Authelia OIDC configuration:
```
      - id: docs
        description: Docspell oidc
        secret: [VERY-LONG-SECRET1]
        public: false
        authorization_policy: one_factor
        consent_mode: implicit
        redirect_uris:
          - https://[DOCS.EXAMPLE.COM]/api/v1/open/auth/openid/authelia/resume # it took me so long get this url...
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signing_algorithm: none # Important to set to NONE. NOT RS256
        response_types:
          - code
        grant_types:
          - authorization_code
```

For the docspell restserver yaml:
```
#
# Docker-Compose
#
version: '3.8'
services:
  restserver:
    image: docspell/restserver:latest
    networks: 
      - traefik-public
      - database
    ports:
      - "7880" # Optional in my setup, still i normally set for not forgetting lol
#    environment: # I'm using file as configuration, not environment. You can use docs to know the variables in case you prefer env.
    depends_on:
      - solr
      - mariadb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role != manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.docker.lbswarm=true
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.docs-http.rule=Host(`[DOCS.EXAMPLE.COM]`)
        - traefik.http.routers.docs-http.entrypoints=http
        - traefik.http.routers.docs-http.middlewares=https-redirect
        - traefik.http.routers.docs-https.rule=Host(`[DOCS.EXAMPLE.COM]`)
        - traefik.http.routers.docs-https.entrypoints=https
        - traefik.http.routers.docs-https.tls=true
        - traefik.http.routers.docs-https.tls.certresolver=cloudflare
        - traefik.http.services.docs.loadbalancer.server.port=7880
        - traefik.http.routers.docs-https.middlewares=authelia@docker
    command:
      - /opt/docspell.conf # Very important! if not set, it will not load config file!
    volumes:
      - /mnt/ceph/docs/docspell.conf:/opt/docspell.conf
```

Now the big config file docspell.conf! Probably a lot can be deleted as it's default, still, i like to see it.
```
ocspell.server {
  app-name = "[EXAMPLE DOCS]"
  app-id = "rest1"
  base-url = "https://[DOCS.EXAMPLE.COM]"
  internal-url = "http://restserver:7880"
  logging {
    format = "Fancy"
    minimum-level = "Info"
    levels = {
      "docspell.oidc" = "Trace" # Can be removed. in my case it helped to debug...
    }
  }
  bind {
    address = "0.0.0.0"
    port = 7880
  }
  server-options {
    enable-http-2 = false # Behind proxy. no need to be exquisite for the connection between this and the proxy!
    max-connections = 1024 # Increased from default
    response-timeout = 45s
  }
  max-item-page-size = 2000 # Increased from default
  max-note-length = 180
  show-classification-settings = true
  auth {
      server-secret = "[YET-ANOTHER-SECRET]"
      session-valid = "30 minutes"
      remember-me {
          enabled = true
          valid = "30 days"
      }
      on-account-source-conflict = "convert"
  }
  download-all {
    max-files = 5000
    max-size = 5000M
  }
  openid =
  [ { enabled = true,
      display = "Authelia"
      provider = {
          provider-id = "authelia",
          client-id = "docs",
          client-secret = "[VERY-LONG-SECRET1]", # Remember this also goes to authelia config!
          scope = "openid profile groups email",
          authorize-url = "https://[AUTH.EXAMPLE.COM]/api/oidc/authorization",
          token-url = "https://[AUTH.EXAMPLE.COM]/api/oidc/token",
          user-url = "https://[AUTH.EXAMPLE.COM]/api/oidc/userinfo",
          sign-key = ""
          sig-algo = "RS256"
      },
      collective-key = "fixed:[COLLECTIVE-NAME]",
      user-key = "preferred_username"
    }
  ]
  oidc-auto-redirect = true # Autologin yay!
  integration-endpoint {
    enabled = true
    priority = "low"
    allowed-ips {
      enabled = true
      ips = [
        "*.*.*.*" # I'm behind a proxy, so... yeah i can do this as http header was failing for me.
      ]
    }
  }
  admin-endpoint {
    # The secret. If empty, the endpoint is disabled.
    secret = "[JUST-ANOTHER-SECRET]"
  }
  full-text-search {
    enabled = true
    backend = "solr"
    solr = {
      url = "http://solr:8983/solr/docspell"
      commit-within = 1000
      log-verbose = false
    }
  }
  backend {
    jdbc {
      url = "jdbc:mariadb://mariadb:3306/docs"
      user = "docs"
      password = "[MYSQL-PASSWORD]"
    }
    database-schema = {
      run-main-migrations = true
      run-fixup-migrations = true
      repair-schema = false
    }
    signup {
      mode = "closed"
    }
    files {
      chunk-size = 524288
      valid-mime-types = [ ]
      default-store = "database"
      stores = {
        database =
          { enabled = true
            type = "default-database"
          }
        filesystem =
          { enabled = false
          }

        minio =
         { enabled = false
         }
      }
    }
    addons = {
      enabled = false
    }
  }
}
```
Hope this information is useful for the next me.

I will also paste some errors i got so people searching for them find this. Without particular order:
```
docs_restserver.1.58hmvb718tbk@node05    | 2022.12.26 17:03:19:0000 [io-comp...] [TRACE] docspell.oidc.CodeFlow.logRequests:172 - HTTP/1.1 GET https://[REDACTED]/api/oidc/userinfo Headers(Authorization: <REDACTED>, Accept: application/json) body=""
docs_restserver.1.58hmvb718tbk@node05    | 2022.12.26 17:03:19:0000 [io-comp...] [ERROR] docspell.oidc.CodeFlow.resp:154 - Error decoding user info response into json!org.http4s.MalformedMessageBodyFailure: Malformed message body: Invalid JSON
docs_restserver.1.58hmvb718tbk@node05    |      at org.http4s.circe.CirceInstances$.$anonfun$defaultCirceParseError$1(CirceInstances.scala:267)
docs_restserver.1.58hmvb718tbk@node05    |      at org.http4s.circe.CirceInstances.$anonfun$jsonDecoderByteBufferImpl$2(CirceInstances.scala:62)
docs_restserver.1.58hmvb718tbk@node05    |      at cats.syntax.EitherOps$.leftMap$extension(either.scala:193)
docs_restserver.1.58hmvb718tbk@node05    |      at org.http4s.circe.CirceInstances.$anonfun$jsonDecoderByteBufferImpl$1(CirceInstances.scala:62)
docs_restserver.1.58hmvb718tbk@node05    |      at scala.util.Either.flatMap(Either.scala:352)
docs_restserver.1.58hmvb718tbk@node05    |      at cats.data.EitherT.$anonfun$subflatMap$1(EitherT.scala:456)
docs_restserver.1.58hmvb718tbk@node05    |      at cats.effect.IOFiber.succeeded(IOFiber.scala:1166)
docs_restserver.1.58hmvb718tbk@node05    |      at cats.effect.IOFiber.runLoop(IOFiber.scala:268)
docs_restserver.1.58hmvb718tbk@node05    |      at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1338)
docs_restserver.1.58hmvb718tbk@node05    |      at cats.effect.IOFiber.run(IOFiber.scala:140)
docs_restserver.1.58hmvb718tbk@node05    |      at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:549)
docs_restserver.1.58hmvb718tbk@node05    | Caused by: io.circe.ParsingFailure: expected json value got 'eyJhbG...' (line 1, column 1)
-
docs_restserver.1.sh7y85d1aj9a@node05    | 2022.12.26 14:02:39:0000 [io-comp...] [INFO ] docspell.oidc.CodeFlowRoutes.userInfo:78 - Resume OAuth/OIDC flow for authelia
docs_restserver.1.sh7y85d1aj9a@node05    | 2022.12.26 14:02:39:0001 [io-comp...] [TRACE] docspell.oidc.CodeFlowRoutes.userInfo:89 - Resume OAuth/OIDC flow from authelia with auth_code=[REDACTED] docs_restserver.1.sh7y85d1aj9a@node05    | 2022.12.26 14:02:39:0002 [io-comp...] [TRACE] docspell.oidc.CodeFlow.apply:46 - Obtaining access_token for provider authelia and code [REDACTED]
docs_restserver.1.sh7y85d1aj9a@node05    | 2022.12.26 14:02:39:0002 [io-comp...] [TRACE] docspell.oidc.CodeFlow.logRequests:172 - HTTP/1.1 POST http://authelia:9091/api/oidc/token Headers(Content-Type: application/x-www-form-urlencoded; charset=UTF-8, Accept: application/json, Content-Length: 340) body="redirect_uri=[REDACTED]&grant_type=authorization_code"
docs_restserver.1.sh7y85d1aj9a@node05    | 2022.12.26 14:02:39:0003 [io-comp...] [ERROR] docspell.oidc.CodeFlow.fetchAccessToken:125 - Error obtaining access token status=401, body={"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method). the passwords don't match"}
docs_restserver.1.sh7y85d1aj9a@node05    | 2022.12.26 14:02:39:0004 [io-comp...] [TRACE] docspell.oidc.CodeFlow.logResponses:181 - HTTP/1.1 401 Unauthorized Headers(Date: Mon, 26 Dec 2022 13:02:39 GMT, Content-Type: application/json;charset=UTF-8, Content-Length: 200, Vary: Accept-Encoding, X-Content-Type-Options: nosniff, Referrer-Policy: strict-origin-when-cross-origin, Permissions-Policy: interest-cohort=(), X-Frame-Options: SAMEORIGIN, X-Xss-Protection: 1; mode=block, Content-Security-Policy: default-src 'none';, Pragma: no-cache, Cache-Control: no-store) body="{"error":"invalid_client","error_description":"Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication me
```
