### ISSUE TITLE
Weird encoding/render characters?

### ISSUE THREAD

**Issue by Enjoyed** [eikek/docspell#1898]
Hello again!

I'm having some trouble troubleshooting or trying to find out why there's weird characters showing on the converted. Here's an example:
![imagen](https://user-images.githubusercontent.com/17934382/209703761-c15356b3-752f-4010-802c-97aafd5322ca.png)

Now, the weird thing is, i can copy-paste these icons, and it's the proper text! Here's the source file shown correctly:
![imagen](https://user-images.githubusercontent.com/17934382/209703883-d297ea3a-b9ee-4967-bd65-da5eff043577.png)

Even the extracted text is correct. It seems to only affect the preview/render, but when i download the file, the weird characters keep on.
There's no visible warn/error/info on browser console nor on the file processing log.

It doesn't affect all. Just... some text? In this example it's the entire document, but i also have documents without any, and documents with maybe a single line of this weird text. Could it be because of docspell missing some font that these pdf use?

Thanks

**Comment by Enjoyed** [comment]
To add more details, here would be the log about the conversion:
```
Sat, December 31st, 2022, 14:14: Converting file Some(ResumenContrato2.pdf) (application/pdf) into a PDF
Sat, December 31st, 2022, 14:14: Storing input to file /tmp/docspell-convert/docspell-ocrmypdf11411127099403049982/infile for running ocrmypdf
Sat, December 31st, 2022, 14:14: Trying to read the PDF using 1 passwords
Sat, December 31st, 2022, 14:14: Running external command: ocrmypdf -l spa --skip-text --deskew -j 1 /tmp/docspell-convert/docspell-ocrmypdf11411127099403049982/infile /tmp/docspell-convert/docspell-ocrmypdf11411127099403049982/out.pdf
Sat, December 31st, 2022, 14:14: Command `ocrmypdf -l spa --skip-text --deskew -j 1 /tmp/docspell-convert/docspell-ocrmypdf11411127099403049982/infile /tmp/docspell-convert/docspell-ocrmypdf11411127099403049982/out.pdf` finished: 0
Sat, December 31st, 2022, 14:14: ocrmypdf stdout:
Sat, December 31st, 2022, 14:14: ocrmypdf stderr: 1 skipping all processing on this page 2 skipping all processing on this page Postprocessing... Optimize ratio: 1.00 savings: 0.1% Output file is a PDF/A-2B (as expected)
Sat, December 31st, 2022, 14:14: Conversion to pdf successful. Saving file.
Sat, December 31st, 2022, 14:14: Closing process: `ocrmypdf -l spa --skip-text --deskew -j 1 /tmp/docspell-convert/docspell-ocrmypdf11411127099403049982/infile /tmp/docspell-convert/docspell-ocrmypdf11411127099403049982/out.pdf`
```
Could it be more an issue from ocrmypdf rather than docspell?

**Comment by eikek** [comment]
It is hard to diagnose from here, but my first guess is that some font is missing on the system that runs joex. This would affect almost all tools that do something with PDFs and it would only affect those PDFs that don't include all the glyphs which is a bit sad imho. Then the fallback font seems to be off as well. You cuold maybe test the pdfs in question on the system by running ocrmypdf by hand and/or pdfinfo etc to look into the pdf. If you have a pdf without any sensible information that you can share, I could take a look as well.

**Comment by Enjoyed** [comment]
Thanks for your time!

You can get the file:
```
wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1dFwkZi4jUIabPkWhogmMFvBmrimrqehY' -O test.pdf
```
I tested it on the same docker container;
```
bash-5.1# ocrmypdf -l spa --skip-text --deskew -j 1 test.pdf outtest.pdf
Scanning contents: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.58page/s]
    1 skipping all processing on this page
    2 skipping all processing on this page
OCR: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.0/2.0 [00:00<00:00, 305.44page/s]
Postprocessing...
PDF/A conversion: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  3.45page/s]
Recompressing JPEGs: 0image [00:00, ?image/s]
Deflating JPEGs: 0image [00:00, ?image/s]
JBIG2: 0item [00:00, ?item/s]
Optimize ratio: 1.00 savings: 0.1%
Output file is a PDF/A-2B (as expected)
```
I used the same command as i saw on the logs, and this result (outtest.pdf) seems to work properly. Just in case i re-uploaded this file via gui, and it seems to throw the same skips:
```
Sat, December 31st, 2022, 19:14: Converting file Some(test.pdf) (application/pdf) into a PDF
Sat, December 31st, 2022, 19:14: Storing input to file /tmp/docspell-convert/docspell-ocrmypdf13296477803091843268/infile for running ocrmypdf
Sat, December 31st, 2022, 19:14: Trying to read the PDF using 1 passwords
Sat, December 31st, 2022, 19:14: Running external command: ocrmypdf -l spa --skip-text --deskew -j 1 /tmp/docspell-convert/docspell-ocrmypdf13296477803091843268/infile /tmp/docspell-convert/docspell-ocrmypdf13296477803091843268/out.pdf
Sat, December 31st, 2022, 19:14: Command `ocrmypdf -l spa --skip-text --deskew -j 1 /tmp/docspell-convert/docspell-ocrmypdf13296477803091843268/infile /tmp/docspell-convert/docspell-ocrmypdf13296477803091843268/out.pdf` finished: 0
Sat, December 31st, 2022, 19:14: ocrmypdf stdout:
Sat, December 31st, 2022, 19:14: ocrmypdf stderr: 1 skipping all processing on this page 2 skipping all processing on this page Postprocessing... Optimize ratio: 1.00 savings: 0.1% Output file is a PDF/A-2B (as expected)
Sat, December 31st, 2022, 19:14: Conversion to pdf successful. Saving file.
Sat, December 31st, 2022, 19:14: Closing process: `ocrmypdf -l spa --skip-text --deskew -j 1 /tmp/docspell-convert/docspell-ocrmypdf13296477803091843268/infile /tmp/docspell-convert/docspell-ocrmypdf13296477803091843268/out.pdf`
```
But, sadly, the result here:
![imagen](https://user-images.githubusercontent.com/17934382/210152350-6c5ce358-7e48-4fde-818f-305cc0315fec.png)

Thanks for your help.

**Comment by eikek** [comment]
Thanks for the details! I need to take a closer look when I have more time. It could be indeed some fonts missing in the container - but then why does it work when executed manually. Hm, could it be that the fonts are not accessible to the docspell user that runs the joex process?

**Comment by Enjoyed** [comment]
Seems like it really is a fonts issue!
Here's the most common warn:
```
    142 IOTLNU+ZurichSans-Light
    148 SDPARV+OpenSans-Regular
    150 QRXVCX+OpenSans-Regular
    152 JAGJIZ+MVBoli
    156 VVAXZX+VodafoneRg-Regular
    158 OPIHHQ+VodafoneRg-Regular
    168 YAHVMA+Cambria-Bold
    180 AESENE+Montserrat-Light
    192 YWFHKK+PTSans-Bold
    210 MYJLLU+Verdana
    224 HWFXOE+ArialMT
    224 PLITJB+Roboto-Light
    224 SYFWCK+ArialMT
    236 ICIHVL+Unknown
    256 EKXQCE+OpenSans-Regular
    260 QPZXUL+Montserrat-Medium
    264 ITCFRB+Munged-LWbV4xkyBu
    289 BERNUP+OpenSans-Regular
    360 SCUAFJ+PTSans-Regular
    376 DTHUUL+Roboto-Bold
    392 GAAAXG+Humnst777BT
    456 HFRDKL+OpenSans-Regular
    520 GSLSKO+OpenSans-Regular
   1022 QDSREI+OpenSans-Regular
   2304 SNPZKF+OpenSans-Regular
   2898 ECAHTO+Humnst777BT
```
And well, the full error as example:
```
 [WARN ] org.apache.pdfbox.pdmodel.font.PDType0Font - No Unicode mapping for CID+233 (233) in font AOFPHQ+Cambria
 [WARN ] org.apache.pdfbox.pdmodel.font.PDType0Font - No Unicode mapping for CID+66 (66) in font AOFPHQ+Cambria
 [WARN ] org.apache.pdfbox.pdmodel.font.PDType0Font - No Unicode mapping for CID+110 (110) in font AOFPHQ+Cambria
 [WARN ] org.apache.pdfbox.pdmodel.font.PDType0Font - No Unicode mapping for CID+243 (243) in font AOFPHQ+Cambria
 [WARN ] org.apache.pdfbox.pdmodel.font.PDType0Font - No Unicode mapping for CID+84 (84) in font DCWWQB+Cambria,Bold
 [WARN ] org.apache.pdfbox.pdmodel.font.PDType0Font - No Unicode mapping for CID+73 (73) in font DCWWQB+Cambria,Bold
```
Now i wonder if my pdf are faulty or there's some error with joex trying to get fonts

**Comment by eikek** [comment]
It is very likely a fonts issue. It cannot find the unicode to a glyph in the pdf. Probably the pdf doesn't contain it itself and the font being loaded doesn't provide it. I tested your pdf on my installation and it worked properly. I think this is only for the docker images, it misses some font that you need for your pdf. if you know which, we could adopt the images to install it. OTOH you mentioned that running the same command manually proudced a correct pdf? Then I really don't know how that can happen…

**Comment by FCUnlimited** [comment]
Hi!
I've got the same error at several pdf's.
Docspell runs on a docker as well here.

I tried to find the difference between the files and the only difference I could finde is in the font properties:
Encoding is different:
**Works: Integrated
Works not: WinAnsiEncoding**

Let me know if I can supply you with more information

**Comment by eikek** [comment]
I think it would help if I could get such a PDF, so I can do some research. Maybe it is possible to generate something with non-sensible information in it?

**Comment by Enjoyed** [comment]
> Update: I just tried your document on the docker version of docspell (current snapshot) and could not reproduce it. Strange! Do you run the provided docker environment or what's your setup?

I dont modify the joex image, here's my docker-compose for joex:
```
joex:
    image: docspell/joex:latest
    command:
      - -J-Xmx1G
    networks: 
      - traefik-public
      - database
    environment:
      - TZ=Europe/Madrid
      - DOCSPELL_JOEX_APP__ID=joex1
      - DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_BASE__URL=http://joex:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL=http://solr:8983/solr/docspell
      - DOCSPELL_JOEX_JDBC_PASSWORD=[REDACTED]
      - DOCSPELL_JOEX_JDBC_URL=jdbc:mariadb://mariadb:3306/docs
      - DOCSPELL_JOEX_JDBC_USER=docs
      - DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER=docker,trivial
      - DOCSPELL_JOEX_CONVERT_HTML__CONVERTER=weasyprint
      - DOCSPELL_JOEX_USER__TASKS_SCAN__MAILBOX_MAIL__CHUNK__SIZE=300
      - DOCSPELL_JOEX_USER__TASKS_SCAN__MAILBOX_MAX__MAILS=20000
      - DOCSPELL_JOEX_SCHEDULER_POOL__SIZE=4
    ports:
      - "7878"
    depends_on:
      - solr
      - mariadb
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role != manager
    volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/ceph/docs/tmp:/tmp
      - /mnt/ceph/docs/docspell.conf:/opt/docspell.conf
```
Re-reading it, could it be due to `DOCSPELL_JOEX_CONVERT_HTML__CONVERTER=weasyprint` ?
Additionally, i tried to [install fonts ](https://stackoverflow.com/a/66593620)to the joex container (google fonts... 1GB+ worth of fonts)

**Comment by eikek** [comment]
Hm, not sure what's going on. I tried this file
```
wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1dFwkZi4jUIabPkWhogmMFvBmrimrqehY' -O test.pdf
```
and I could not reproduce the issue, the converted file looked fine….The `=weasyprint` is only used when converting html files, I don't think it is related.

**Comment by eikek** [comment]
Oh wait, can you try `snapshot` instead of `latest` images? Maybe something is odd with the `latest` image but working on the most current one.

**Comment by Enjoyed** [comment]
I will guess by snapshot you mean the nightly image? https://hub.docker.com/r/docspell/joex/tags?page=1
Seems to still happen with this build :(
```
  joex:
    image: docspell/joex:nightly
```

![imagen](https://user-images.githubusercontent.com/17934382/211410451-a7bbb1b2-cfc8-42e5-b8c2-3d005617f0d7.png)

**Comment by FCUnlimited** [comment]
I ve got the same weird result with the test.pdf
I printed such a pdf and included all fonts into the pdf. In this case it works all fine.

**Comment by eikek** [comment]
This is strange, I cannot reproduce it here on my machine. I tried the pdf from @Enjoyed (downloaded from google docs). The result looks like this (using docker of latest stable version):

![Selection_051](https://user-images.githubusercontent.com/701128/211908891-281adb54-64cd-45b2-920c-11c2c40998be.png)

@FCUnlimited can you maybe share a document that I could play with?

**Comment by Enjoyed** [comment]
Interestingly enough, i did some tests!

I installed docker on my windows machine, using the same settings (docspell.conf) and stuff, and it happens anyways!
![imagen](https://user-images.githubusercontent.com/17934382/212416684-224ef909-87a9-451a-bd3f-b4c531256d38.png)
![imagen](https://user-images.githubusercontent.com/17934382/212416750-727cb08b-9977-49a8-80d4-fed9d4dae24a.png)

Here's the docker compose (everything without volumes, so everything "new"):
```
#
# Docker-Compose
#
version: '3.8'
services:
  restserver:
    image: docspell/restserver:latest
    restart: unless-stopped
    container_name: restserver
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Madrid
      - DOCSPELL_SERVER_INTERNAL__URL=http://restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=value2
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=value3
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=dbpass
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:postgresql://db:5432/dbname
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=dbuser
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=value1
      - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
    depends_on:
      - solr
      - db
    command:
      - /opt/docspell.conf
    volumes:
      - ./docspell.conf:/opt/docspell.conf

  joex:
    image: docspell/joex:latest
    restart: unless-stopped
    container_name: joex
    command:
      - -J-Xmx1G
    ports:
      - "7878:7878"
    depends_on:
      - solr
      - db
    volumes:
      - ./docspell.conf:/opt/docspell.conf

  consumedir:
    image: docspell/dsc:latest
    restart: unless-stopped
    container_name: consumedir
    command:
      - dsc
      - "-d"
      - "http://restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:value1"
      - "/opt/docs"
    depends_on:
      - restserver

  db:
    image: postgres:15.1
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname

  solr:
    image: solr:9
    container_name: solr
    restart: unless-stopped
    command:
      - solr-precreate
      - docspell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s
```

and the docspell.conf:
```
docspell.server {
  app-name = "[redacted] Docs"
  app-id = "rest1"
  base-url = "http://localhost:7880"
  internal-url = "http://localhost:7880"
  logging {
    format = "Fancy"
    minimum-level = "Info"
    levels = {
      "docspell.oidc" = "Trace"
    }
  }
  bind {
    address = "0.0.0.0"
    port = 7880
  }
  server-options {
    enable-http-2 = false
    max-connections = 1024
    response-timeout = 45s
  }
  max-item-page-size = 2000
  max-note-length = 180
  show-classification-settings = true
  auth {
      server-secret = "value3"
      session-valid = "30 minutes"
      remember-me {
          enabled = true
          valid = "30 days"
      }
      on-account-source-conflict = "convert"
  }
  download-all {
    max-files = 5000

    # The maximum (uncompressed) size of the zip file contents.
    max-size = 5000M
  }
  openid =
  [ { enabled = false,
      display = "Authelia"
      provider = {
          provider-id = "authelia",
          client-id = "docs",
          client-secret = "[redacted]",
          scope = "openid profile groups email",
          authorize-url = "https://[redacted]/api/oidc/authorization",
          token-url = "https://[redacted]/api/oidc/token",
          user-url = "https://[redacted]/api/oidc/userinfo",
          sign-key = ""
          sig-algo = "RS256"
      },
      collective-key = "fixed:[redacted]",
      user-key = "preferred_username"
    }
  ]
  oidc-auto-redirect = false
  integration-endpoint {
    enabled = true
    priority = "low"
    allowed-ips {
      enabled = true
      ips = [
        "*.*.*.*"
      ]
    }
  }
  admin-endpoint {
    # The secret. If empty, the endpoint is disabled.
    secret = "value2"
  }
  full-text-search {
    enabled = true
    backend = "solr"
    solr = {
      url = "http://solr:8983/solr/docspell"
      commit-within = 1000
      log-verbose = false
    }
  }
  backend {
    jdbc {
      url = "jdbc:postgresql://db:5432/dbname"
      user = "dbuser"
      password = "dbpass"
    }
    database-schema = {
      run-main-migrations = true
      run-fixup-migrations = true
      repair-schema = false
    }
    signup {
      mode = "open"
    }
    files {
      chunk-size = 524288
      valid-mime-types = [ ]
      default-store = "database"
      stores = {
        database =
          { enabled = true
            type = "default-database"
          }
        filesystem =
          { enabled = false
          }

        minio =
         { enabled = false
         }
      }
    }
    addons = {
      enabled = false
    }
  }
}
```


So, i thought, why not use the "default" values.... but still the same :/ i dont know anymore. Here's the docker-compose default that gives me error (simply with environment and without docspell.conf volume/command)
```
#
# Docker-Compose
#
version: '3.8'
services:
  restserver:
    image: docspell/restserver:latest
    restart: unless-stopped
    container_name: restserver
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Madrid
      - DOCSPELL_SERVER_INTERNAL__URL=http://restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=value2
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=value3
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=dbpass
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:postgresql://db:5432/dbname
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=dbuser
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=value1
      - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
    depends_on:
      - solr
      - db
#    volumes:
#      - ./docspell.conf:/opt/docspell.conf

  joex:
    image: docspell/joex:latest
    restart: unless-stopped
    container_name: joex
    command:
      - -J-Xmx1G
    environment:
      - TZ=Europe/Madrid
      - DOCSPELL_JOEX_APP__ID=joex1
      - DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_BASE__URL=http://joex:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL=http://solr:8983/solr/docspell
      - DOCSPELL_JOEX_JDBC_PASSWORD=dbpass
      - DOCSPELL_JOEX_JDBC_URL=jdbc:postgresql://db:5432/dbname
      - DOCSPELL_JOEX_JDBC_USER=dbuser
      - DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER=docker,trivial
      - DOCSPELL_JOEX_CONVERT_HTML__CONVERTER=weasyprint
      - DOCSPELL_JOEX_USER__TASKS_SCAN__MAILBOX_MAIL__CHUNK__SIZE=300
      - DOCSPELL_JOEX_USER__TASKS_SCAN__MAILBOX_MAX__MAILS=20000
      - DOCSPELL_JOEX_SCHEDULER_POOL__SIZE=4
    ports:
      - "7878:7878"
    depends_on:
      - solr
      - db
    volumes:
      - ./docspell.conf:/opt/docspell.conf

  consumedir:
    image: docspell/dsc:latest
    restart: unless-stopped
    container_name: consumedir
    command:
      - dsc
      - "-d"
      - "http://restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:value1"
      - "/opt/docs"
    depends_on:
      - restserver

  db:
    image: postgres:15.1
    container_name: db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname

  solr:
    image: solr:9
    container_name: solr
    restart: unless-stopped
    command:
      - solr-precreate
      - docspell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s
```
