### ISSUE TITLE
Processing queue problems using S3 MinIO Backend

### ISSUE THREAD

**Issue by acaciochinato** [eikek/docspell#2040]
Hello! 

I'm testing a new setup with docker and MinIO to serve as object storage but all the files I upload stay in the process queue waiting to be processed for hours. Maybe I'm missing some settings in the docker-compose envs?

Using the default docker-compose provided, I removed all the dbs envs and inserted this:
```
      - DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE=minio
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ACCESS__KEY=test
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_BUCKET=test
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENABLED=true
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENDPOINT=http://minio:9000
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_SECRET__KEY=
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_TYPE=s3
```

Here's my compose:

```
version: '3.8'
services:
  restserver:
    image: docspell/restserver:latest
    container_name: docspell-restserver
    restart: unless-stopped
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=admin123
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=integration-password123
      - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
      - DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD=
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
      - DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE=minio
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ACCESS__KEY=test
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_BUCKET=test
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENABLED=true
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENDPOINT=http://minio:9000
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_SECRET__KEY=
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_TYPE=s3
    depends_on:
      - solr
  joex:
    image: docspell/joex:latest
    container_name: docspell-joex
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_JOEX_APP__ID=joex1
      - DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_BASE__URL=http://localhost:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER=docker,trivial
      - DOCSPELL_JOEX_CONVERT_HTML__CONVERTER=weasyprint
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
      - DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE=minio
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ACCESS__KEY=test
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_BUCKET=test
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENABLED=true
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENDPOINT=http://minio:9000
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_SECRET__KEY=
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_TYPE=s3   
    ports:
      - "7878:7878"
    depends_on:
      - solr
  consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:integration-password123"
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - ./docs:/opt/docs
    depends_on:
      - restserver
  solr:
    image: solr:9
    container_name: docspell-solr
    restart: unless-stopped
    volumes:
      - docspell-solr_data:/var/solr
    command:
      - bash
      - -c
      - 'precreate-core docspell; exec solr -f -Dsolr.modules=analysis-extras'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s

volumes:
  docspell-solr_data:
```

**Comment by eikek** [comment]
Thank you for the detailed report! There must be something going wrong in the file store library. I'll take a look as soon as I can.

**Comment by jan-oratowski** [comment]
@eikek it looks like you have a bug in your docker-compose:
Joex environment variables should start with: DOCSPELL_JOEX_ instead of DOCSPELL_SERVER_

This is my docker-compose and it works fine (the only difference is the usage of environment variables):

```
  restserver:
    image: docspell/restserver:latest
    container_name: docspell-restserver
    restart: unless-stopped
    ports:
      - "7880:7880"
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=<redacted>
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=<redacted>
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:mariadb://services1:3306/docspell
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=docspell
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=<redacted>
      - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
      - DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD=
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
      - DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE=minio
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ACCESS__KEY=<redacted>
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_BUCKET=docspell
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENABLED=true
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_ENDPOINT=http://services1:9001
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_SECRET__KEY=<redacted>
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_MINIO_TYPE=s3
    depends_on:
      - solr

  joex:
    image: docspell/joex:latest
    container_name: docspell-joex
    ## For more memory add corresponding arguments, like below. Also see
    ## https://docspell.org/docs/configure/#jvm-options
    # command:
    #   - -J-Xmx3G
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - DOCSPELL_JOEX_APP__ID=joex1
      - DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_BASE__URL=http://docspell-joex:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_JOEX_JDBC_PASSWORD=<redacted>
      - DOCSPELL_JOEX_JDBC_URL=jdbc:mariadb://services1:3306/docspell
      - DOCSPELL_JOEX_JDBC_USER=docspell
      - DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER=docker,trivial
      - DOCSPELL_JOEX_CONVERT_HTML__CONVERTER=weasyprint
      - DOCSPELL_JOEX_FILES_DEFAULT__STORE=minio
      - DOCSPELL_JOEX_FILES_STORES_MINIO_ACCESS__KEY=<redacted>
      - DOCSPELL_JOEX_FILES_STORES_MINIO_BUCKET=docspell
      - DOCSPELL_JOEX_FILES_STORES_MINIO_ENABLED=true
      - DOCSPELL_JOEX_FILES_STORES_MINIO_ENDPOINT=http://services1:9001
      - DOCSPELL_JOEX_FILES_STORES_MINIO_SECRET__KEY=<redacted>
      - DOCSPELL_JOEX_FILES_STORES_MINIO_TYPE=s3
    ports:
      - "7878:7878"
    depends_on:
      - solr

```

I honestly think that the way variables have to be named is confusing, but can't do anything about that.
