### ISSUE TITLE
[Kubernetes] Wrong PostgreSQL mount path and other Kubernetes manifest issues

### ISSUE THREAD

**Issue by TheAnachronism** [eikek/docspell#2498]
I'm currently in the process of generally reworking my entire docspell setup, and decided to switch to a Kubernetes-based deployment. I was pleased to find that there were already `kustomize` ready manifests available, but I've found some issues with them.

### 1. The volume mount for the `postgres` stateful set doesn't quite work.
Due to how volume mounting works, it can happen that there is a `lost+found` directory created within the specified `/var/lib/postgresql/data` path. This causes Postgres to fail on startup, due to the not-empty directory.

To fix this, a simple `subPath` statement can be added:
```yaml
volumeMounts:
  - name: postgres-data
    mountPath: /var/lib/postgresql/data
    subPath: pgdata
```

### 2. Wrong permissions for Apache Solr in `/var/solr`
Sadly, the volume mounts causes solr to have issues with file permissions in the `/var/solr` directory. To make sure, that the file permissions are always correct, an _initContainer_ should be added:

```yaml
template:
  metadata:
    labels:
      app: solr
  spec:
    initContainers:
      - name: fix-permissions
        image: busybox
        command:
          - "sh"
          - "-c"
          - "chown -R 8983:8983 /var/solr"
        volumeMounts:
          - name: solr-data
            mountPath: /var/solr
```
