### ISSUE TITLE
Is the default docker-compose dsc container supposed to scan for files automatically?

### ISSUE THREAD

**Issue by rpgdev** [eikek/docspell#2510]
Hi, I'm wondering if using the default dsc config in https://github.com/eikek/docspell/blob/a7bc973345d9f9b39d03239cf0f92d910c416848/docker/docker-compose/docker-compose.yml#L90 is dsc supposed to automatically scan in files dropped in ./docs without further involvement from me? Or do I need to do something else?

**Comment by eikek** [comment]
It should watch the directory and push files as soon as they arrive. No involvement necessary otherwise.

**Comment by rpgdev** [comment]
@eikek it's not working for some reason, what can I do to verify the cause?

**Comment by eikek** [comment]
Are you using the standard compose file with no change? If not, how does it look like? Are you using perhaps a network file system to watch?

**Comment by rpgdev** [comment]
I changed it slightly:
```
consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:${DOCSPELL_SERVER_INTEGRATION_PASSWORD}"
      - "/opt/docs"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DATA}/documents/docspell_watch:/opt/docs
    depends_on:
      - restserver
```

Every other the ${VARS} are just environment variables for OMV to replace. Inspecting the container for consumedir I can see the real values being replaced for them.
