### ISSUE TITLE
filesystem backend - jobs fail

### ISSUE THREAD

**Issue by ceastus** [eikek/docspell#2566]
I had it working using docker compose with the default database backend, and then I decided to switch to a filesystem backend. I changed the default-store and set directory, enabled, and type. See the config posted below.

Upload via web UI was fast, but the image preview and OCR jobs failed. The doc log from the jobs page shows success even though there were errors.

![image](https://github.com/eikek/docspell/assets/13847454/b0802323-f1ee-4c10-9561-3e1421f17c40)

```
Mon, March 25th, 2024, 13:35: ============ Start processing 1901825-BBONE-AI-Spec-Sheet.pdf ============
Mon, March 25th, 2024, 13:35: Checking for duplicate files
Mon, March 25th, 2024, 13:35: Creating new item with 1 attachment(s)
Mon, March 25th, 2024, 13:35: Creating item finished in 54 ms
Mon, March 25th, 2024, 13:35: Not an archive: application/pdf
Mon, March 25th, 2024, 13:35: Converting file Some(1901825-BBONE-AI-Spec-Sheet.pdf) (application/pdf) into a PDF
Mon, March 25th, 2024, 13:35: Storing input to file /tmp/docspell-convert/docspell-ocrmypdf2639067247808477411/infile for running ocrmypdf
Mon, March 25th, 2024, 13:35: Trying to read the PDF using 0 passwords
Mon, March 25th, 2024, 13:35: PDF conversion failed: Error: End-of-File, expected line at offset 0. Go without PDF file
Mon, March 25th, 2024, 13:35: Starting text extraction for 1 files
Mon, March 25th, 2024, 13:35: Extracting text for attachment 1901825-BBONE-AI-Spec-Sheet.pdf
Mon, March 25th, 2024, 13:35: Trying to strip text from pdf using pdfbox.
Mon, March 25th, 2024, 13:35: Stripping text from PDF resulted in an error: Error: End-of-File, expected line at offset 0. Trying with OCR.
Mon, March 25th, 2024, 13:35: Cannot extract text: File `MimeType(application,octet-stream,None)` not supported. Try with converted file
Mon, March 25th, 2024, 13:35: Cannot extract text
Mon, March 25th, 2024, 13:35: Extracting text for attachment 1901825-BBONE-AI-Spec-Sheet.pdf finished in 26 ms
Mon, March 25th, 2024, 13:35: Storing extracted texts …
Mon, March 25th, 2024, 13:35: Extracted text stored.
Mon, March 25th, 2024, 13:35: Updating SOLR index

```

The container logs:
```
docspell-restserver  | 2024.03.25 13:35:50:0000 [io-comp...] [INFO ] docspell.backend.ops.OUpload.saveFile:218 - Receiving file File(Some(1901825-BBONE-AI-Spec-Sheet.pdf),Some(MimeType(application,pdf,None)),Stream(..))
docspell-restserver  | 2024.03.25 13:35:50:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 POST /api/v1/sec/upload/item
docspell-restserver  | 2024.03.25 13:35:50:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 200 OK
docspell-joex0       | 2024.03.25 13:35:50:0000 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 POST /internal/pubsub
docspell-joex0       | 2024.03.25 13:35:50:0001 [io-comp...] [INFO ] org.http4s.server.middleware.Logger - HTTP/1.1 200 OK
docspell-joex0       | 2024.03.25 13:35:50:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:50.847743414Z Info 3prqWaJyQ.../1/process-item/High: ============ Start processing 1901825-BBONE-AI-Spec-Sheet.pdf ============ (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:50:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:50.885575829Z Info 3prqWaJyQ.../1/process-item/High: Creating new item with 1 attachment(s) (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:50:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:50.939770099Z Info 3prqWaJyQ.../1/process-item/High: Creating item finished in 54 ms (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:51:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:51.135025622Z Info 3prqWaJyQ.../1/process-item/High: Converting file Some(1901825-BBONE-AI-Spec-Sheet.pdf) (application/pdf) into a PDF (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:50:0001 [io-comp...] [ERROR] docspell.scheduler.impl.LogSink.logInternal:51 - >>> 2024-03-25T13:35:51.169989277Z Error 3prqWaJyQ.../1/process-item/High: PDF conversion failed: Error: End-of-File, expected line at offset 0. Go without PDF file (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:51:0001 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:51.185839974Z Info 3prqWaJyQ.../1/process-item/High: Starting text extraction for 1 files (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:50:0002 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:51.203325789Z Info 3prqWaJyQ.../1/process-item/High: Stripping text from PDF resulted in an error: Error: End-of-File, expected line at offset 0. Trying with OCR.  (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:50:0001 [io-comp...] [WARN ] docspell.scheduler.impl.LogSink.logInternal:45 - >>> 2024-03-25T13:35:51.213113993Z Warn 3prqWaJyQ.../1/process-item/High: Cannot extract text: File `MimeType(application,octet-stream,None)` not supported. Try with converted file (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-solr        | 2024-03-25 13:35:51.252 INFO  (qtp2061774051-21-null-81) [c: s: r: x:docspell t:null-81] o.a.s.u.p.LogUpdateProcessorFactory webapp=/solr path=/update params={commitWithin=1000&overwrite=true&wt=json}{add=[item.3R4SZbaUDPJ-eSwQw6TUG8f-YfemCXBDbDA-uFy2VwG95TL (1794505442587574272), 3R4SZbaUDPJ-eSwQw6TUG8f-YfemCXBDbDA-uFy2VwG95TL.8GJ2zf1a8w2-5oAJsVxxQnn-8q6cq2WYyZ1-8dP7PBdamGg (1794505442591768576)]} 0 5
docspell-joex0       | 2024.03.25 13:35:51:0000 [io-comp...] [ERROR] docspell.scheduler.impl.LogSink.logInternal:51 - >>> 2024-03-25T13:35:51.213538983Z Error 3prqWaJyQ.../1/process-item/High: Cannot extract text (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:51:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:51.215318739Z Info 3prqWaJyQ.../1/process-item/High: Extracting text for attachment 1901825-BBONE-AI-Spec-Sheet.pdf finished in 26 ms (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:51:0000 [io-comp...] [INFO ] docspell.analysis.nlp.StanfordNerAnnotator.makePipeline:39 - Creating german Stanford NLP NER classifier...
docspell-joex0       | 2024.03.25 13:35:51:0002 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:51.256088130Z Info 3prqWaJyQ.../1/process-item/High: Text extraction finished in 69 ms. (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:51:0001 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:51.257853870Z Info 3prqWaJyQ.../1/process-item/High: Creating preview images for 1 files… (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:50:0003 [io-comp...] [ERROR] docspell.scheduler.impl.LogSink.logInternal:49 - >>> 2024-03-25T13:35:51.263606117Z Error 3prqWaJyQ.../1/process-item/High: Creating preview images failed, continuing without it.
docspell-joex0       | java.io.IOException: Error: End-of-File, expected line at offset 0
docspell-joex0       |  at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1092)
docspell-joex0       |  at org.apache.pdfbox.pdfparser.COSParser.parseHeader(COSParser.java:1605)
docspell-joex0       |  at org.apache.pdfbox.pdfparser.COSParser.parsePDFHeader(COSParser.java:1588)
docspell-joex0       |  at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:157)
docspell-joex0       |  at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:136)
docspell-joex0       |  at org.apache.pdfbox.Loader.loadPDF(Loader.java:224)
docspell-joex0       |  at org.apache.pdfbox.Loader.loadPDF(Loader.java:196)
docspell-joex0       |  at org.apache.pdfbox.Loader.loadPDF(Loader.java:176)
docspell-joex0       |  at org.apache.pdfbox.Loader.loadPDF(Loader.java:159)
docspell-joex0       |  at docspell.extract.pdfbox.PdfLoader$.$anonfun$readBytes1$1(PdfLoader.scala:19)
docspell-joex0       |  at delay @ docspell.extract.pdfbox.PdfLoader$.readBytes1(PdfLoader.scala:19)
docspell-joex0       |  at main$ @ docspell.joex.Main$.main(Main.scala:15)
docspell-joex0       |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex0       |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex0       |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex0       |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex0       |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex0       |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex0       |  at modify @ fs2.internal.Scope.close(Scope.scala:262)
docspell-joex0       |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex0       |  at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
docspell-joex0       |  at as @ docspell.joex.Main$.$anonfun$run$10(Main.scala:49)
docspell-joex0       |  at get @ fs2.internal.Scope.openScope(Scope.scala:275)
docspell-joex0       |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex0       |  at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
docspell-joex0       |  (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:51:0000 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:51.265161847Z Info 3prqWaJyQ.../1/process-item/High: Retrieving page count for 1 files… (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:51:0000 [io-comp...] [WARN ] docspell.scheduler.impl.LogSink.logInternal:45 - >>> 2024-03-25T13:35:51.269885062Z Warn 3prqWaJyQ.../1/process-item/High: Error obtaining pages count: Error: End-of-File, expected line at offset 0 (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k81ksAy75zU", task: "process-item", group: "1", jobInfo: "3prqWaJyQ.../1/process-item/High")
docspell-joex0       | 2024.03.25 13:35:50:0002 [io-comp...] [INFO ] docspell.scheduler.impl.LogSink.logInternal:41 - >>> 2024-03-25T13:35:51.287399690Z Info 3prqWaJyQ.../1/process-item/High: Starting text analysis (jobId: "3prqWaJyQaf-NKtfPtc4Ehk-sSj8f4TQbFq-k8
```

docker-compose.yml:

```
services:

  # The restserver and joex containers defined here are configured
  # using env variables. Both must connect to the same database and
  # solr instance. More information on configuring can be found here:
  # https://docspell.org/docs/configure
  #
  # Please replace the values of the following with a custom secret
  # string:
  #
  # - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET
  # - DOCSPELL_SERVER_AUTH_SERVER__SECRET
  # - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE
  #   (use the same value at the consumedir container!)
  #
  # After creating an account, you may want to set signup mode to
  # "closed" or to "invite". When using invite, you must also set
  # DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD to some
  # secret.
  restserver:
    image: docspell/restserver:latest
    container_name: docspell-restserver
    restart: unless-stopped
    ports:
      - "7880:7880"
    environment:
      - TZ=Etc/UTC
      - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=admin123
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=dbpass
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:postgresql://db:5432/dbname
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=dbuser
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=integration-password123
      - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
      - DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD=
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
      - DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE=filesystem
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_DIRECTORY=/mnt/docspell
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_ENABLED=true
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_TYPE=file-system
    depends_on:
      - solr
      - db
    volumes:
      - /storage/docspell:/mnt/docspell

  joex0:
    image: docspell/joex:latest
    container_name: docspell-joex0
    ## For more memory add corresponding arguments, like below. Also see
    ## https://docspell.org/docs/configure/#jvm-options
    # command:
    #   - -J-Xmx3G
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
      - DOCSPELL_JOEX_APP__ID=joex0
      - DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME=joex0
      - DOCSPELL_JOEX_SCHEDULER_NAME=joex0
      - DOCSPELL_JOEX_BASE__URL=http://docspell-joex0:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_JOEX_JDBC_PASSWORD=dbpass
      - DOCSPELL_JOEX_JDBC_URL=jdbc:postgresql://db:5432/dbname
      - DOCSPELL_JOEX_JDBC_USER=dbuser
      - DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER=docker,trivial
      - DOCSPELL_JOEX_CONVERT_HTML__CONVERTER=weasyprint
      - DOCSPELL_SERVER_BACKEND_FILES_DEFAULT__STORE=filesystem
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_DIRECTORY=/mnt/docspell
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_ENABLED=true
      - DOCSPELL_SERVER_BACKEND_FILES_STORES_FILESYSTEM_TYPE=file-system
    ports:
      - "7878:7878"
    depends_on:
      - solr
      - db
    volumes:
      - /storage/docspell:/mnt/docspell
    ## Uncomment when using the "docker" runner with addons
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    #   - /tmp:/tmp

  # The consumedir container watches a directory for files to upload
  # to docspell restserver. This uses the `dsc` tool. For information
  # on the available options, see `dsc --help`.
  # https://github.com/docspell/dsc
  #
  # The value after `Docspell-Integration` must match the secret
  # specified at the restserver via
  # DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE.
  #
  # The --not-matches "**/.*" option is to exclude hidden files.
  consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:integration-password123"
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - ./docs:/opt/docs
      - /storage/docspell:/mnt/docspell
    depends_on:
      - restserver

  db:
    image: postgres:16.2
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - docspell-postgres_data:/var/lib/postgresql/data/
      - /storage/docspell:/mnt/docspell
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=dbname

  solr:
    image: solr:9
    container_name: docspell-solr
    restart: unless-stopped
    volumes:
      - docspell-solr_data:/var/solr
      - /storage/docspell:/mnt/docspell
    command:
      - bash
      - -c
      - 'precreate-core docspell; exec solr -f -Dsolr.modules=analysis-extras'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s

volumes:
  docspell-postgres_data:
  docspell-solr_data:
```

The storage is accessible. The file is there, and it can be viewed from the web UI. It does not have a preview image. It has not been full-text indexed. Reprocessing does not help.
![image](https://github.com/eikek/docspell/assets/13847454/d2308c69-7fc5-4aea-9c41-9d5ad8ff55f8)

![image](https://github.com/eikek/docspell/assets/13847454/4d173dfc-10ed-496d-b12d-627c31019556)
