### ISSUE TITLE
Docker Consumer Directory Questiosn 

### ISSUE THREAD

**Issue by typkrft** [eikek/docspell#448]
I modified the docker-compose.yml and docspell.conf provided in this repo to use folders, ports, and container names I've specified. Everything seems to work with the exception of the consumer directory. 

1. In the docspell.conf am I supposed to replace the ${Variable} with values or are they pulling from somewhere? I've specified the variables in my .env. Just curious because I seemed to have to change the variables in the conf, but documentation seems like it pulls them from somewhere. 
2. Do I need to include the scripts like consumerdir.sh in some volume path?
3. In the folder I specified as the docker volume in the consumerdir service I've added a folder that corresponds with the name of my collective and added a pdf.

**Comment by eikek** [comment]
Hi @typkrft ,

1. The `${Variable}` terms are replaced by either values from the config or environment variables (in that order, iirc). The all-upper-case names usually refer to environment variables. AFAIU they are defined in the `.env` file. But if you know the values anyways, you can put them directly into the config file. After all, docspell needs the concrete value on startup…. Not sure why they are partly defined as env variables, it might be related to how people manage their containers or that values can be shared among containers. I'm sure @totti4ever can help here better than me. 
2. No, the script is provided by the container. The container executes the script and you can change some options via env variables. (the container specifies an ENTRYPOINT and arguments)
3. Hmm… maybe this is the culprit. Docspell needs a directory where it can list subdirectories that match collective names. And looking into the `consumedir.dockerfile`, the path in the container is hardcoded to `/opt/docs`. So you need to mount your "real" directory to this location. Then create in your folder a subfolder with the name of the collective and put files in this subdirectory. Also, the env variable `DOCSPELL_HEADER_VALUE` must define the same value as used in the `docspell.conf` in the `integration-endpoint` section. In the default setup, this is ensured by reusing this env variable in the config file, to share it between both containers.

If problems persist, maybe you could share some of your configs and possibly error messages if they occur (maybe the consumedir container shows some logs)?

**Comment by typkrft** [comment]
Thanks for the quick reply. 

From the docspell-consumedir service logs:

```
- Result from checkfile: failed

- Checking file failed, skipping the file.

-> Some uploads failed.

The file '/opt/docs/my.pdf' appeared below '/opt/docs'

---- Processing /opt/docs/my.pdf ----------

- Checking if /opt/docs/my.pdf has been uploaded to http://docspell-restserver:7880/api/v1/open/integration/item already

- Check file via  -H Docspell-Integration:: http://docspell-restserver:7880/api/v1/open/integration/checkfile/my.pdf/fa2e494e4d4d330b1184c17fde1a2a501be0bd229560187baf031e6d9d0e192b

Checking file failed!

```

My Configs

dataManagementStack.yml

```YAML
version: "3.7"

########################### NETWORKS
networks:
  t2_proxy:
    external:
      name: t2_proxy

########################### SERVICES
services:
# All services / apps go below this line

  docspell-restserver:
    image: eikek0/docspell:restserver-LATEST
    container_name: docspell-restserver
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "9023:7880"
    volumes:
      - ./docspell/config/docspell.conf:/opt/docspell.conf
    depends_on:
      - docspell-solr
#    environment: 
#      - PUID=$PUID
#      - PGID=$PGID
#      - TZ=$TZ
    labels:
    # SUI
      - sui.enabled=true
      - sui.name=DOCSPELL
      - sui.icon=text-box-search-outline
      - sui.url=https://docs.my.url
    # Watchtower
      # - "com.centurylinklabs.watchtower.enable=true"
    # Traefik
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.docspell-rtr.entrypoints=https"
      - "traefik.http.routers.docspell-rtr.rule=Host(`docs.$DOMAINNAME`)"
      - "traefik.http.routers.docspell-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.docspell-rtr.middlewares=chain-oauth@file" 
#      - "traefik.http.routers.docspell-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      ## HTTP Services
      - "traefik.http.routers.docspell-rtr.service=docspell-svc"
      - "traefik.http.services.docspell-svc.loadbalancer.server.port=7880"
      
  docspell-joex:
    image: eikek0/docspell:joex-LATEST
    container_name: docspell-joex
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "9027:7878"
    volumes:
      - ./docspell/config/docspell.conf:/opt/docspell.conf
    depends_on:
      - docspell-solr
 #   environment:
 #     - PUID=$PUID
 #     - PGID=$PGID
 #     - TZ=$TZ

  docspell-consumedir:
    image: eikek0/docspell:consumedir-LATEST
    container_name: docspell-consumedir
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
 #   environment:
 #     - PUID=$PUID
 #     - PGID=$PGID
 #     - TZ=$TZ
    volumes:
      - /volume1/Files/Document Upload:/opt/docs
    depends_on:
      - docspell-restserver

  docspell-db:
    image: postgres:11.7
    container_name: docspell-db
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - ./docspell/db:/var/lib/postgresql/data/
#    environment:
#      - PUID=$PUID
#      - PGID=$PGID
#      - TZ=$TZ
      - POSTGRES_USER=$DOCSPELL_DB_USER
      - POSTGRES_PASSWORD=$DOCSPELL_DB_PASS
      - POSTGRES_DB=$DOCSPELL_DB_NAME

  docspell-solr:
    image: solr:8
    container_name: docspell-solr
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
#    environment:
#      - PUID=$PUID
#      - PGID=$PGID
#      - TZ=$TZ
    volumes:
      - ./docspell/solr:/var/solr
    command:
      - solr-precreate
      - docspell
    healthcheck:
      test: ["CMD", "curl", "f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s
```

docpsell.conf
```
docspell.server {
  base-url = "http://localhost:7880"
  bind {
    address = "0.0.0.0"
  }
  integration-endpoint {
    enabled = true
    http-header {
      enabled = true
      header-value = MYSECRET1
    }
  }
  # Configuration of the full-text search engine.
  full-text-search {
    enabled = true
    recreate-key = ""
    solr = {
      url = "http://docspell-solr:8983/solr/docspell"
    }
  }
  backend {
    jdbc {
      url = "jdbc:"postgresql"://"docspell-db":"5432"/"docspellDB
      user = MYUSER1
      password = MYSECRET2
    }
  }
}

docspell.joex {
  base-url = "http://docspell-joex:7878"
  bind {
    address = "0.0.0.0"
  }
  jdbc {
    url = "jdbc:"postgresql"://"docspell-db":"5432"/"docspellDB
    user = MYUSER1
    password = MYSECRET2
  }
  full-text-search {
    enabled = true
    solr = {
      url = "http://docspell-solr:8983/solr/docspell"
    }
  }
  scheduler {
    pool-size = 1
  }
}
```
.env
```
# Universal Variables
  # System
    PUID=1026
    PGID=100
    TZ=America/New_York
  # Docker
    COMPOSE_HTTP_TIMEOUT=200
  # Networking
    DOMAINNAME=my.url

DOCSPELL_HEADER_VALUE=MYSECRET1
DOCSPELL_DB_TYPE=postgresql
DOCSPELL_DB_HOST=docspell-db
DOCSPELL_DB_PORT=5432
DOCSPELL_DB_NAME=docspellDB
DOCSPELL_DB_USER=MYUSER1
DOCSPELL_DB_PASS=MYSECRET2


```
