### ISSUE TITLE
select words in imported documents (paypal)

### ISSUE THREAD

**Issue by vakilando** [eikek/docspell#859]
I have a little problem that I can't solve whatever I try:
In all but 2 by a Scan Mailbox task imported mails from *paypal* I can't select words. Yes, only Paypal....!?

- But I can select words/sentences in the original mail in my Thunderbird inbox.
- But I can see the "extracted data" as text from the imported mails in docspell.
- But I can select the text in the "original file" when opened in docspell

What I tried:
- I tried to "re-process" such a document - without success.
- I tried the task that clears the full-text index and re-indexes all your data again - without success (as expected).
- I deleted the document and uploaded the .eml file (saved mail from thunderbird) - without success.
- I deleted the document and imported it again by a Scan Mailbox task - without success. 

This may be important:
The two imported Paypal mails where I *can* select text:
- are not the oldest or newest... (range: 02. - 06.2021)
- are mails where I sent money to a friend. All other mails are mails where I buyed a product fom ebay or so.

**Comment by eikek** [comment]
Good catch! I just checked my files and I also have some paypal mails where I can't select the text in the resulting PDF. 

I could imagine that there is some font missing on the system and wkhtmltopdf then produces graphics instead of text commands. I guess there need to be some more fonts installed, or the html can be tweaked to remove the corresponding styles. It also may result from a font that would be loaded by the browser normally and wkhtmltopdf can't for some reason… Just guessing here, I suspect *some* font issue :).

As a workaround (not very convenient, but might be helpful), you can open the "original file" from the menu which displays the HTML file in the browser and there you can select text (this is the HTML part of the mail).

**Comment by eikek** [comment]
So, it's indeed a bit bad luck. The mail contains html which defines special fonts inside (I will never understand why people need to create these crazy html mails…). Apparently some paypal mails don't have these font declarations. The cause is this block of css inside the html:
```css
@font-face {
  font-family: PayPal-Sans;
  font-style: normal;
  font-weight: 400;
  src: local('PayPalSansSmall-Regular'), url('https://www.paypalobjects.com/ui-web/paypal-sans-small/1-0-0/PayPalSansSmall-Regular.eot');
  /* IE9 Compat Modes */
  src: local('PayPalSansSmall-Regular'),
    url('https://www.paypalobjects.com/ui-web/paypal-sans-small/1-0-0/PayPalSansSmall-Regular.woff2') format('woff2'),
    /* Moderner Browsers */
    url('https://www.paypalobjects.com/ui-web/paypal-sans-small/1-0-0/PayPalSansSmall-Regular.woff') format('woff'),
    /* Modern Browsers */
    url('https://www.paypalobjects.com/ui-web/paypal-sans-small/1-0-0/PayPalSansSmall-Regular.svg#69ac2c9fc1e0803e59e06e93859bed03') format('svg');
  /* Legacy iOS */
  /* Fallback font for - MS Outlook older versions (2007,13, 16)*/
  mso-font-alt: 'Calibri';
}

@font-face {
  font-family: PayPal-Sans;
  font-style: normal;
  font-weight: 500;

  src: local('PayPalSansSmall-Medium'), url('https://www.paypalobjects.com/ui-web/paypal-sans-small/1-0-0/PayPalSansSmall-Medium.eot');
  /* IE9 Compat Modes */
  src: local('PayPalSansSmall-Medium'), url('https://www.paypalobjects.com/ui-web/paypal-sans-small/1-0-0/PayPalSansSmall-Medium.woff2') format('woff2'),
    /* Moderner Browsers */
    url('https://www.paypalobjects.com/ui-web/paypal-sans-small/1-0-0/PayPalSansSmall-Medium.woff') format('woff'),
    /* Modern Browsers */
    url('https://www.paypalobjects.com/ui-web/paypal-sans-small/1-0-0/PayPalSansSmall-Medium.svg#69ac2c9fc1e0803e59e06e93859bed03') format('svg');
  /* Legacy iOS */
  /* Fallback font for - MS Outlook older versions (2007,13, 16)*/
  mso-font-alt: 'Calibri';
}
```
It's enough to replace `PayPal-Sans` with just `Sans` and it works. I have no idea currently how to work around this. Usually declaring fonts like this works, but these seem not to.
